import { existsSync } from "node:fs";
import { mkdir, readFile, readdir, stat, writeFile } from "node:fs/promises";
import { basename, dirname, join, resolve } from "node:path";

const repo = "Lolotronop/trurpchat";
const keyPath = resolve("private-keys/trurpchat-updater.key");
const latestPath = resolve("latest.json");
const tauriConfigPath = resolve("frontend/src-tauri/tauri.conf.json");
const frontendPackagePath = resolve("frontend/package.json");
const cargoTomlPath = resolve("frontend/src-tauri/Cargo.toml");
const nsisBundleDir = resolve("frontend/src-tauri/target/release/bundle/nsis");

type LatestManifest = {
  version: string;
  notes?: string;
  pub_date?: string;
  platforms?: Record<string, { signature: string; url: string }>;
};

function incrementPatch(version: string) {
  const clean = version.trim().replace(/^v/, "");
  const [major = "0", minor = "0", patch = "0"] = clean.split(".");
  return `${Number(major)}.${Number(minor)}.${Number(patch) + 1}`;
}

async function readJson<T>(path: string): Promise<T> {
  return JSON.parse(await readFile(path, "utf8")) as T;
}

async function writeJson(path: string, value: unknown) {
  await writeFile(path, `${JSON.stringify(value, null, 2)}\n`);
}

async function setProjectVersion(version: string) {
  const tauriConfig = await readJson<Record<string, unknown>>(tauriConfigPath);
  tauriConfig.version = version;
  await writeJson(tauriConfigPath, tauriConfig);

  const frontendPackage = await readJson<Record<string, unknown>>(frontendPackagePath);
  frontendPackage.version = version;
  await writeJson(frontendPackagePath, frontendPackage);

  const cargoToml = await readFile(cargoTomlPath, "utf8");
  await writeFile(cargoTomlPath, cargoToml.replace(/^version = "[^"]+"/m, `version = "${version}"`));
}

async function prepareManifest({ increment }: { increment: boolean }) {
  const manifest = await readJson<LatestManifest>(latestPath);
  const version = increment ? incrementPatch(manifest.version) : manifest.version.trim().replace(/^v/, "");

  manifest.version = version;
  manifest.pub_date = new Date().toISOString();
  manifest.notes = manifest.notes || `Windows release ${version}`;
  manifest.platforms = {};

  await writeJson(latestPath, manifest);
  await setProjectVersion(version);

  return version;
}

async function run(command: string[], cwd = process.cwd()) {
  const signingPrivateKey = existsSync(keyPath) ? await readFile(keyPath, "utf8") : undefined;

  const proc = Bun.spawn(command, {
    cwd,
    stdout: "inherit",
    stderr: "inherit",
    stdin: "inherit",
    env: {
      ...process.env,
      ...(signingPrivateKey ? { TAURI_SIGNING_PRIVATE_KEY: signingPrivateKey } : {}),
      TAURI_SIGNING_PRIVATE_KEY_PATH: keyPath,
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD: process.env.TAURI_SIGNING_PRIVATE_KEY_PASSWORD ?? "",
    },
  });

  const exitCode = await proc.exited;
  if (exitCode !== 0) {
    throw new Error(`${command.join(" ")} failed with exit code ${exitCode}`);
  }
}

async function findNsisArtifact(version: string) {
  const files = await readdir(nsisBundleDir);
  const sigFiles = files.filter((file) => file.endsWith(".exe.sig"));
  if (sigFiles.length === 0) {
    throw new Error(`No Windows NSIS .exe.sig file found in ${nsisBundleDir}`);
  }

  const matchingVersion = sigFiles.find((file) => file.includes(version));
  const sigFile = matchingVersion ?? (await newestFile(sigFiles));
  const exeFile = sigFile.slice(0, -".sig".length);
  if (!files.includes(exeFile)) {
    throw new Error(`Found ${sigFile}, but matching ${exeFile} is missing`);
  }

  return {
    exePath: join(nsisBundleDir, exeFile),
    sigPath: join(nsisBundleDir, sigFile),
    exeFile,
  };
}

async function ensureNsisSignature(version: string) {
  const files = await readdir(nsisBundleDir);
  const exeFiles = files.filter((file) => file.endsWith(".exe") && !file.endsWith(".sig"));
  if (exeFiles.length === 0) {
    throw new Error(`No Windows NSIS .exe file found in ${nsisBundleDir}`);
  }

  const matchingVersion = exeFiles.find((file) => file.includes(version));
  const exeFile = matchingVersion ?? (await newestFile(exeFiles));
  const sigPath = join(nsisBundleDir, `${exeFile}.sig`);
  if (existsSync(sigPath)) return;

  console.log(`Signing ${exeFile} because no .sig file was generated by the build`);
  await run(
    [
      "bun",
      "run",
      "tauri",
      "signer",
      "sign",
      "-f",
      "../private-keys/trurpchat-updater.key",
      "-p",
      process.env.TAURI_SIGNING_PRIVATE_KEY_PASSWORD ?? "",
      join("src-tauri/target/release/bundle/nsis", exeFile),
    ],
    resolve("frontend"),
  );
}

async function newestFile(files: string[]) {
  const filesWithMtime = await Promise.all(
    files.map(async (file) => ({
      file,
      mtimeMs: (await stat(join(nsisBundleDir, file))).mtimeMs,
    })),
  );

  filesWithMtime.sort((a, b) => b.mtimeMs - a.mtimeMs);
  return filesWithMtime[0].file;
}

async function finalizeManifest(version: string) {
  const artifact = await findNsisArtifact(version);
  const signature = (await readFile(artifact.sigPath, "utf8")).trim();
  const assetName = encodeURIComponent(basename(artifact.exePath));

  const manifest = await readJson<LatestManifest>(latestPath);
  manifest.version = version;
  manifest.pub_date = manifest.pub_date || new Date().toISOString();
  manifest.platforms = {
    "windows-x86_64": {
      signature,
      url: `https://github.com/${repo}/releases/download/v${version}/${assetName}`,
    },
  };

  await writeJson(latestPath, manifest);
}

async function openFolder(path: string) {
  if (process.platform === "win32") {
    await run(["explorer", path]);
    return;
  }

  if (process.platform === "darwin") {
    await run(["open", path]);
    return;
  }

  await run(["xdg-open", path]);
}

async function main() {
  const shouldBuild = process.argv.includes("--build");
  const shouldIncrement = !process.argv.includes("--no-increment");
  const shouldOpenFolder = process.argv.includes("--open-folder");

  await mkdir(dirname(keyPath), { recursive: true });

  if (shouldBuild && !existsSync(keyPath)) {
    throw new Error(`Missing updater signing key at ${keyPath}`);
  }

  const version = await prepareManifest({ increment: shouldIncrement });
  console.log(
    `Prepared Windows update manifest for v${version}${shouldIncrement ? "" : " without incrementing"}`,
  );

  if (!shouldBuild) {
    if (shouldOpenFolder) await openFolder(nsisBundleDir);
    return;
  }

  await run(["bun", "run", "tauri", "build"], resolve("frontend"));
  await ensureNsisSignature(version);
  await finalizeManifest(version);
  console.log(`Built signed Windows release v${version} and finalized latest.json`);

  if (shouldOpenFolder) await openFolder(nsisBundleDir);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
